//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace EnsureRisk.ServiceRiskController {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WebServiceRiskSoap", Namespace="http://tempuri.org/")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(object[]))]
    public partial class WebServiceRisk : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetRiskTreeStringOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetDefaultRiskOperationCompleted;
        
        private System.Threading.SendOrPostCallback SaveRiskOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetRiskTreeIDOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetElementDataOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WebServiceRisk() {
            this.Url = global::EnsureRisk.Properties.Settings.Default.EnsureRisk_ServiceRiskController_WebServiceRisk;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetRiskTreeStringCompletedEventHandler GetRiskTreeStringCompleted;
        
        /// <remarks/>
        public event GetDefaultRiskCompletedEventHandler GetDefaultRiskCompleted;
        
        /// <remarks/>
        public event SaveRiskCompletedEventHandler SaveRiskCompleted;
        
        /// <remarks/>
        public event GetRiskTreeIDCompletedEventHandler GetRiskTreeIDCompleted;
        
        /// <remarks/>
        public event GetElementDataCompletedEventHandler GetElementDataCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetRiskTreeString", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetRiskTreeString(object[] param) {
            object[] results = this.Invoke("GetRiskTreeString", new object[] {
                        param});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void GetRiskTreeStringAsync(object[] param) {
            this.GetRiskTreeStringAsync(param, null);
        }
        
        /// <remarks/>
        public void GetRiskTreeStringAsync(object[] param, object userState) {
            if ((this.GetRiskTreeStringOperationCompleted == null)) {
                this.GetRiskTreeStringOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetRiskTreeStringOperationCompleted);
            }
            this.InvokeAsync("GetRiskTreeString", new object[] {
                        param}, this.GetRiskTreeStringOperationCompleted, userState);
        }
        
        private void OnGetRiskTreeStringOperationCompleted(object arg) {
            if ((this.GetRiskTreeStringCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetRiskTreeStringCompleted(this, new GetRiskTreeStringCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetDefaultRisk", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetDefaultRisk() {
            object[] results = this.Invoke("GetDefaultRisk", new object[0]);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void GetDefaultRiskAsync() {
            this.GetDefaultRiskAsync(null);
        }
        
        /// <remarks/>
        public void GetDefaultRiskAsync(object userState) {
            if ((this.GetDefaultRiskOperationCompleted == null)) {
                this.GetDefaultRiskOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetDefaultRiskOperationCompleted);
            }
            this.InvokeAsync("GetDefaultRisk", new object[0], this.GetDefaultRiskOperationCompleted, userState);
        }
        
        private void OnGetDefaultRiskOperationCompleted(object arg) {
            if ((this.GetDefaultRiskCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetDefaultRiskCompleted(this, new GetDefaultRiskCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SaveRisk", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet SaveRisk(System.Data.DataSet ds) {
            object[] results = this.Invoke("SaveRisk", new object[] {
                        ds});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void SaveRiskAsync(System.Data.DataSet ds) {
            this.SaveRiskAsync(ds, null);
        }
        
        /// <remarks/>
        public void SaveRiskAsync(System.Data.DataSet ds, object userState) {
            if ((this.SaveRiskOperationCompleted == null)) {
                this.SaveRiskOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSaveRiskOperationCompleted);
            }
            this.InvokeAsync("SaveRisk", new object[] {
                        ds}, this.SaveRiskOperationCompleted, userState);
        }
        
        private void OnSaveRiskOperationCompleted(object arg) {
            if ((this.SaveRiskCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SaveRiskCompleted(this, new SaveRiskCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetRiskTreeID", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetRiskTreeID(object[] param) {
            object[] results = this.Invoke("GetRiskTreeID", new object[] {
                        param});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void GetRiskTreeIDAsync(object[] param) {
            this.GetRiskTreeIDAsync(param, null);
        }
        
        /// <remarks/>
        public void GetRiskTreeIDAsync(object[] param, object userState) {
            if ((this.GetRiskTreeIDOperationCompleted == null)) {
                this.GetRiskTreeIDOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetRiskTreeIDOperationCompleted);
            }
            this.InvokeAsync("GetRiskTreeID", new object[] {
                        param}, this.GetRiskTreeIDOperationCompleted, userState);
        }
        
        private void OnGetRiskTreeIDOperationCompleted(object arg) {
            if ((this.GetRiskTreeIDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetRiskTreeIDCompleted(this, new GetRiskTreeIDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetElementData", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetElementData(string sp, string tablename) {
            object[] results = this.Invoke("GetElementData", new object[] {
                        sp,
                        tablename});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void GetElementDataAsync(string sp, string tablename) {
            this.GetElementDataAsync(sp, tablename, null);
        }
        
        /// <remarks/>
        public void GetElementDataAsync(string sp, string tablename, object userState) {
            if ((this.GetElementDataOperationCompleted == null)) {
                this.GetElementDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetElementDataOperationCompleted);
            }
            this.InvokeAsync("GetElementData", new object[] {
                        sp,
                        tablename}, this.GetElementDataOperationCompleted, userState);
        }
        
        private void OnGetElementDataOperationCompleted(object arg) {
            if ((this.GetElementDataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetElementDataCompleted(this, new GetElementDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void GetRiskTreeStringCompletedEventHandler(object sender, GetRiskTreeStringCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetRiskTreeStringCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetRiskTreeStringCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void GetDefaultRiskCompletedEventHandler(object sender, GetDefaultRiskCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetDefaultRiskCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetDefaultRiskCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void SaveRiskCompletedEventHandler(object sender, SaveRiskCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SaveRiskCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SaveRiskCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void GetRiskTreeIDCompletedEventHandler(object sender, GetRiskTreeIDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetRiskTreeIDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetRiskTreeIDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void GetElementDataCompletedEventHandler(object sender, GetElementDataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetElementDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetElementDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591