//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnsureRisk.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StringResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EnsureRisk.Resources.StringResources", typeof(StringResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dam. CM: {0} {1}.
        /// </summary>
        internal static string ACUM_CM_DAMAGE {
            get {
                return ResourceManager.GetString("ACUM_CM_DAMAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acum. Dam: .
        /// </summary>
        internal static string ACUM_DAMAGE {
            get {
                return ResourceManager.GetString("ACUM_DAMAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acum. Likelihood: .
        /// </summary>
        internal static string ACUM_LIKELIHOOD {
            get {
                return ResourceManager.GetString("ACUM_LIKELIHOOD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dam. Risks: {0} {1}.
        /// </summary>
        internal static string ACUM_RISK_DAMAGE {
            get {
                return ResourceManager.GetString("ACUM_RISK_DAMAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max. Damage.:.
        /// </summary>
        internal static string ACUM_VALUE {
            get {
                return ResourceManager.GetString("ACUM_VALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string AddButton {
            get {
                return ResourceManager.GetString("AddButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Countermeasure.
        /// </summary>
        internal static string AddCMMenu {
            get {
                return ResourceManager.GetString("AddCMMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Risk.
        /// </summary>
        internal static string AddRiskMenu {
            get {
                return ResourceManager.GetString("AddRiskMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string CancelButton {
            get {
                return ResourceManager.GetString("CancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string CloseButton {
            get {
                return ResourceManager.GetString("CloseButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collapsed?.
        /// </summary>
        internal static string CollapsedCheck {
            get {
                return ResourceManager.GetString("CollapsedCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color Content.
        /// </summary>
        internal static string ColorContentLabel {
            get {
                return ResourceManager.GetString("ColorContentLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color Theme.
        /// </summary>
        internal static string ColorThemeLabel {
            get {
                return ResourceManager.GetString("ColorThemeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a color.
        /// </summary>
        internal static string ColorToolTip {
            get {
                return ResourceManager.GetString("ColorToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        internal static string ConfirmPasswordText {
            get {
                return ResourceManager.GetString("ConfirmPasswordText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected user:.
        /// </summary>
        internal static string CONNECTED_STRING {
            get {
                return ResourceManager.GetString("CONNECTED_STRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        internal static string COPY_MENU {
            get {
                return ResourceManager.GetString("COPY_MENU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete .
        /// </summary>
        internal static string DELETE_MESSAGE {
            get {
                return ResourceManager.GetString("DELETE_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string DeleteButton {
            get {
                return ResourceManager.GetString("DeleteButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Countermeasure.
        /// </summary>
        internal static string DeleteCMMenu {
            get {
                return ResourceManager.GetString("DeleteCMMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Risk.
        /// </summary>
        internal static string DeleteRiskMenu {
            get {
                return ResourceManager.GetString("DeleteRiskMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Design Area Resolution.
        /// </summary>
        internal static string DesignAreaToolTip {
            get {
                return ResourceManager.GetString("DesignAreaToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diagonal.
        /// </summary>
        internal static string DiagonalCheck {
            get {
                return ResourceManager.GetString("DiagonalCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diagram Name.
        /// </summary>
        internal static string DiagramNameLabel {
            get {
                return ResourceManager.GetString("DiagramNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diagram Values.
        /// </summary>
        internal static string DiagramValuesGroupB {
            get {
                return ResourceManager.GetString("DiagramValuesGroupB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable.
        /// </summary>
        internal static string DisableValue {
            get {
                return ResourceManager.GetString("DisableValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string EditButton {
            get {
                return ResourceManager.GetString("EditButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Countermeasure.
        /// </summary>
        internal static string EditCMMenu {
            get {
                return ResourceManager.GetString("EditCMMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Risk.
        /// </summary>
        internal static string EditRiskMenu {
            get {
                return ResourceManager.GetString("EditRiskMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable.
        /// </summary>
        internal static string EnableValue {
            get {
                return ResourceManager.GetString("EnableValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string ExitMenu {
            get {
                return ResourceManager.GetString("ExitMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acum. Likelihood.
        /// </summary>
        internal static string ExpectedLKLabel {
            get {
                return ResourceManager.GetString("ExpectedLKLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export diagram as Image.
        /// </summary>
        internal static string EXPORT_IMAGE {
            get {
                return ResourceManager.GetString("EXPORT_IMAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Father.
        /// </summary>
        internal static string FatherText {
            get {
                return ResourceManager.GetString("FatherText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field required in blank.
        /// </summary>
        internal static string FIELD_REQUIRED {
            get {
                return ResourceManager.GetString("FIELD_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter by Damage.
        /// </summary>
        internal static string FilterTRGroupB {
            get {
                return ResourceManager.GetString("FilterTRGroupB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View current diagram as Tree.
        /// </summary>
        internal static string FISH_MENU_TOOLTIP {
            get {
                return ResourceManager.GetString("FISH_MENU_TOOLTIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From Top?.
        /// </summary>
        internal static string FromTopCheck {
            get {
                return ResourceManager.GetString("FromTopCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go Back!.
        /// </summary>
        internal static string GoBackTooltip {
            get {
                return ResourceManager.GetString("GoBackTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Environment.
        /// </summary>
        internal static string ListEnviroment {
            get {
                return ResourceManager.GetString("ListEnviroment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Languaje.
        /// </summary>
        internal static string ListLanguaje {
            get {
                return ResourceManager.GetString("ListLanguaje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server Setting.
        /// </summary>
        internal static string ListServerSetting {
            get {
                return ResourceManager.GetString("ListServerSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string LoginButton {
            get {
                return ResourceManager.GetString("LoginButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string LoginMenu {
            get {
                return ResourceManager.GetString("LoginMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string LoginTitle {
            get {
                return ResourceManager.GetString("LoginTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logoff.
        /// </summary>
        internal static string LOGOFF {
            get {
                return ResourceManager.GetString("LOGOFF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import project.
        /// </summary>
        internal static string MENU_IMPORT {
            get {
                return ResourceManager.GetString("MENU_IMPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scope this.
        /// </summary>
        internal static string MENU_SCOPE {
            get {
                return ResourceManager.GetString("MENU_SCOPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move Countermeasure.
        /// </summary>
        internal static string MoveCMMenu {
            get {
                return ResourceManager.GetString("MoveCMMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move Risk.
        /// </summary>
        internal static string MoveRiskMenu {
            get {
                return ResourceManager.GetString("MoveRiskMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string NoButton {
            get {
                return ResourceManager.GetString("NoButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Probability field must be numeric.
        /// </summary>
        internal static string NUMERIC_FIELD {
            get {
                return ResourceManager.GetString("NUMERIC_FIELD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password and Confirm password fields do not match.
        /// </summary>
        internal static string PASSWORD_MATCH {
            get {
                return ResourceManager.GetString("PASSWORD_MATCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string PasswordText {
            get {
                return ResourceManager.GetString("PasswordText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste.
        /// </summary>
        internal static string PASTE_MENU {
            get {
                return ResourceManager.GetString("PASTE_MENU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print Diagram.
        /// </summary>
        internal static string PRINT_DIAGRAM {
            get {
                return ResourceManager.GetString("PRINT_DIAGRAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prob.: .
        /// </summary>
        internal static string PROBABILITY {
            get {
                return ResourceManager.GetString("PROBABILITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value of the probability is greater than 100.
        /// </summary>
        internal static string PROBABILITY_FIELD {
            get {
                return ResourceManager.GetString("PROBABILITY_FIELD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Probability (%).
        /// </summary>
        internal static string ProbabilityLabel {
            get {
                return ResourceManager.GetString("ProbabilityLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart.
        /// </summary>
        internal static string REBOOT {
            get {
                return ResourceManager.GetString("REBOOT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resolution.
        /// </summary>
        internal static string ResolutionMenu {
            get {
                return ResourceManager.GetString("ResolutionMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detail.
        /// </summary>
        internal static string RiskDetailText {
            get {
                return ResourceManager.GetString("RiskDetailText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Risk Diagram.
        /// </summary>
        internal static string RiskDiagramTitle {
            get {
                return ResourceManager.GetString("RiskDiagramTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Risk.
        /// </summary>
        internal static string RiskTitle {
            get {
                return ResourceManager.GetString("RiskTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role List.
        /// </summary>
        internal static string RoleListMenu {
            get {
                return ResourceManager.GetString("RoleListMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role Name.
        /// </summary>
        internal static string RoleNameText {
            get {
                return ResourceManager.GetString("RoleNameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles.
        /// </summary>
        internal static string RolesGroupBox {
            get {
                return ResourceManager.GetString("RolesGroupBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scale.
        /// </summary>
        internal static string ScaleGroupB {
            get {
                return ResourceManager.GetString("ScaleGroupB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        internal static string SelectButton {
            get {
                return ResourceManager.GetString("SelectButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a Damage.
        /// </summary>
        internal static string SelectTopRiskTitle {
            get {
                return ResourceManager.GetString("SelectTopRiskTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server Address.
        /// </summary>
        internal static string ServerAddressText {
            get {
                return ResourceManager.GetString("ServerAddressText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set.
        /// </summary>
        internal static string SetButton {
            get {
                return ResourceManager.GetString("SetButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string SettingsMenu {
            get {
                return ResourceManager.GetString("SettingsMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Short Name.
        /// </summary>
        internal static string ShortNameText {
            get {
                return ResourceManager.GetString("ShortNameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        internal static string StartTooltip {
            get {
                return ResourceManager.GetString("StartTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles.
        /// </summary>
        internal static string TabRoles {
            get {
                return ResourceManager.GetString("TabRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Values.
        /// </summary>
        internal static string TabValues {
            get {
                return ResourceManager.GetString("TabValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Damage Definition.
        /// </summary>
        internal static string TopRiskDefinitionText {
            get {
                return ResourceManager.GetString("TopRiskDefinitionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Damages List.
        /// </summary>
        internal static string TopRiskList {
            get {
                return ResourceManager.GetString("TopRiskList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Damage.
        /// </summary>
        internal static string TopRiskText {
            get {
                return ResourceManager.GetString("TopRiskText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Damage.
        /// </summary>
        internal static string TopRiskTitle {
            get {
                return ResourceManager.GetString("TopRiskTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit.
        /// </summary>
        internal static string UnitText {
            get {
                return ResourceManager.GetString("UnitText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Data.
        /// </summary>
        internal static string UserDataTitle {
            get {
                return ResourceManager.GetString("UserDataTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Description.
        /// </summary>
        internal static string UserDescriptionText {
            get {
                return ResourceManager.GetString("UserDescriptionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User List.
        /// </summary>
        internal static string UserListMenu {
            get {
                return ResourceManager.GetString("UserListMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        internal static string UserText {
            get {
                return ResourceManager.GetString("UserText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value: .
        /// </summary>
        internal static string VALUE {
            get {
                return ResourceManager.GetString("VALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong User or Password!!!.
        /// </summary>
        internal static string WRONG_PASSWORD {
            get {
                return ResourceManager.GetString("WRONG_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string YesButton {
            get {
                return ResourceManager.GetString("YesButton", resourceCulture);
            }
        }
    }
}
