//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnsureRisk.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.3.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("WebService")]
        public string EnsureRisk {
            get {
                return ((string)(this["EnsureRisk"]));
            }
            set {
                this["EnsureRisk"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{0:#0.0}")]
        public string DecimalsStringFormat {
            get {
                return ((string)(this["DecimalsStringFormat"]));
            }
            set {
                this["DecimalsStringFormat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int DecimalFractionalDigits {
            get {
                return ((int)(this["DecimalFractionalDigits"]));
            }
            set {
                this["DecimalFractionalDigits"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost/EnsureRiskWS/WebServiceGroupe.asmx")]
        public string EnsureRisk_GroupService_WebServiceGroupe {
            get {
                return ((string)(this["EnsureRisk_GroupService_WebServiceGroupe"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost/EnsureRiskWS/WebServiceAuthentication.asmx")]
        public string EnsureRisk_ServiceAuthentication_WebServiceAuthentication {
            get {
                return ((string)(this["EnsureRisk_ServiceAuthentication_WebServiceAuthentication"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost/EnsureRiskWS/WebServiceRisk.asmx")]
        public string EnsureRisk_ServiceRiskController_WebServiceRisk {
            get {
                return ((string)(this["EnsureRisk_ServiceRiskController_WebServiceRisk"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost/EnsureRiskWS/WebServiceRole.asmx")]
        public string EnsureRisk_ServiceRoleController_WebServiceRole {
            get {
                return ((string)(this["EnsureRisk_ServiceRoleController_WebServiceRole"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost/EnsureRiskWS/WebServiceTopRisk.asmx")]
        public string EnsureRisk_ServiceTopRiskController_WebServiceTopRisk {
            get {
                return ((string)(this["EnsureRisk_ServiceTopRiskController_WebServiceTopRisk"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost/EnsureRiskWS/WebServiceUser.asmx")]
        public string EnsureRisk_ServiceUserController_WebServiceUser {
            get {
                return ((string)(this["EnsureRisk_ServiceUserController_WebServiceUser"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost/EnsureRiskWS/WebServiceWBS.asmx")]
        public string EnsureRisk_ServiceWBS_WebServiceWBS {
            get {
                return ((string)(this["EnsureRisk_ServiceWBS_WebServiceWBS"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost/EnsureRiskWS/WebServiceProject.asmx")]
        public string EnsureRisk_ServiceProject_WebServiceProject {
            get {
                return ((string)(this["EnsureRisk_ServiceProject_WebServiceProject"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost/EnsureRiskWS/WebServiceClasificator.asmx")]
        public string EnsureRisk_ServiceClasifications_WebServiceClasificator {
            get {
                return ((string)(this["EnsureRisk_ServiceClasifications_WebServiceClasificator"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost/EnsureRiskWS/WebServiceMyLog.asmx")]
        public string EnsureRisk_ServiceLog_WebServiceMyLog {
            get {
                return ((string)(this["EnsureRisk_ServiceLog_WebServiceMyLog"]));
            }
        }
    }
}
